### ISSUE TITLE
Device pixel ratio is missed

### ISSUE THREAD

**Issue by Reon90** [maierfelix/nvk-examples#2]
Mac OS with retina display:
![image](https://user-images.githubusercontent.com/8707222/54380825-6a600c00-469d-11e9-8a6f-cfe7b91440b7.png)

**Comment by maierfelix** [comment]
I have a hackintosh, so I cannot test this. Does the triangle example look correct?

Edit: `glfwGetWindowContentScale` seems to be related to this. Should I expose it's scale factors in the `VulkanWindow` class?

**Comment by Reon90** [comment]
@maierfelix how can I test it?

**Comment by maierfelix** [comment]
@Reon90 What does the triangle example look like?

You can open a browser console and type in `devicePixelRatio`. Take this value and use it in the example. I'm not sure though how you would use it then, try playing around with it. I unfortunately never worked with Retina displays

**Comment by Reon90** [comment]
@maierfelix the triangle example is the same.
I think we have to fix it in window creation by glfw.

**Comment by maierfelix** [comment]
@Reon90 found this in the GLFW FAQ [here](https://www.glfw.org/faq.html):

4.3 - Why is my output in the lower-left corner of the window?
You are passing the window size, which is in screen coordinates, to glViewport, which works with pixels. On macOS with a Retina display, and possibly on other platforms in the future, screen coordinates and pixels do not map 1:1. Use the framebuffer size, which is in pixels, instead of the window size. See the Window handling guide for details.

**Comment by maierfelix** [comment]
@Reon90 Latest nvk version `0.3.7` now exposes 3 new properties in `VulkanWindow`:
 - frameBufferWidth
 - frameBufferHeight
 - devicePixelRatio

Could you try replacing `win.width` -> `win.frameBufferWidth` and `win.height` -> `win.frameBufferHeight`?

**Comment by Reon90** [comment]
@maierfelix yes it works.
![image](https://user-images.githubusercontent.com/8707222/54687433-9a3f6180-4b2c-11e9-92b0-fc11a515c512.png)

**Comment by maierfelix** [comment]
@Reon90 Thanks for the feedback! Considering this closed
